name: 'Commit Message Check'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_commit.message }}
      - name: Check Line Length
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^.{4,72}'
          flags: 'gms'
          error: 'The maximum line length of 72 characters is exceeded.'
          excludeDescription: 'true'
          excludeTitle: 'true'
            #accessToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Check for Resolves / Fixes
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '(Resolves|Fixes) AlmaLinux\/build-system\#[0-9]+$'
          error: 'You need at least one "Resolves|Fixes: <issue link>" line.'
          excludeTitle: 'true'
          excludeDescription: 'true'
            #accessToken: ${{ secrets.GITHUB_TOKEN }}
